export {default as Login} from './Login/Login';
export {default as SignUp} from './SignUp/SignUp';
export {default as Insingts} from './Insingts/Insingts';
export {default as Library} from './Library/Library';
export {default as Profile} from './Profile/Profile';
export {default as Signals} from './Signals/Signals';
export {default as Social} from './Social/Social';
export {default as DetailArticle} from './Library/DetailArticle';
export {default as AllArticles} from './Library/AllArticles';
