import imagePath from '../constants/imagePath';

export default {
  Metaverse: [
    {
      id: 1,
      currencyName: 'Internet Computer',
      price24h: '$3.49',
      pricePercentage: '0.23%',
      marketCap: '$1,563,769,793',
      rank: 1,
      rankName: 'icp',
      img: imagePath.BNB,
    },
    {
      id: 2,
      currencyName: 'Render',
      price24h: '$2.16',
      pricePercentage: '-1.9%',
      marketCap: '$80,563,769,793',
      rank: 2,
      rankName: 'rndr',
      img: imagePath.Bitcoin,
    },
    {
      id: 3,
      currencyName: 'The Sandbox',
      price24h: '$0.16',
      pricePercentage: '-2.9%',
      marketCap: '$30,563,769,793',
      rank: 3,
      rankName: 'sand',
      img: imagePath.Cardano,
    },
    {
      id: 4,
      currencyName: 'Decentraland',
      price24h: '$1.26',
      pricePercentage: '3.2%',
      marketCap: '$54,563,769,793',
      rank: 4,
      rankName: 'mana',
      img: imagePath.Ethereum,
    },
    {
      id: 5,
      currencyName: 'FLOKi',
      price24h: '$1.26',
      pricePercentage: '3.2%',
      marketCap: '$54,563,769,793',
      rank: 5,
      rankName: 'floki',
      img: imagePath.Solana,
    },
    {
      id: 6,
      currencyName: 'Illuvium',
      price24h: '$1.26',
      pricePercentage: '3.2%',
      marketCap: '$54,563,769,793',
      rank: 6,
      rankName: 'ilv',
      img: imagePath.Tether,
    },
    {
      id: 7,
      currencyName: 'Enjin Coin',
      price24h: '$1.26',
      pricePercentage: '3.2%',
      marketCap: '$54,563,769,793',
      rank: 7,
      rankName: 'enj',
      img: imagePath.Usdcoin,
    },
    {
      id: 8,
      currencyName: 'Merit Circle',
      price24h: '$1.26',
      pricePercentage: '3.2%',
      marketCap: '$54,563,769,793',
      rank: 8,
      rankName: 'rnc',
      img: imagePath.XRP,
    },
  ],
  Metagovernance: [
    {
      id: 1,
      currencyName: 'Internet Computer',
      price24h: '$3.49',
      pricePercentage: '0.23%',
      marketCap: '$1,563,769,793',
      rank: 3,
      rankName: 'icp',
      img: imagePath.BNB,
    },
    {
      id: 2,
      currencyName: 'Render',
      price24h: '$2.16',
      pricePercentage: '-1.9%',
      marketCap: '$80,563,769,793',
      rank: 1,
      rankName: 'rndr',
      img: imagePath.Bitcoin,
    },
    {
      id: 3,
      currencyName: 'The Sandbox',
      price24h: '$0.16',
      pricePercentage: '-2.9%',
      marketCap: '$30,563,769,793',
      rank: 2,
      rankName: 'sand',
      img: imagePath.Cardano,
    },
    {
      id: 4,
      currencyName: 'Decentraland',
      price24h: '$1.26',
      pricePercentage: '3.2%',
      marketCap: '$54,563,769,793',
      rank: 4,
      rankName: 'mana',
      img: imagePath.Ethereum,
    },
    {
      id: 5,
      currencyName: 'FLOKi',
      price24h: '$1.26',
      pricePercentage: '3.2%',
      marketCap: '$54,563,769,793',
      rank: 5,
      rankName: 'floki',
      img: imagePath.Solana,
    },
    {
      id: 6,
      currencyName: 'Illuvium',
      price24h: '$1.26',
      pricePercentage: '3.2%',
      marketCap: '$54,563,769,793',
      rank: 6,
      rankName: 'ilv',
      img: imagePath.Tether,
    },
    {
      id: 7,
      currencyName: 'Enjin Coin',
      price24h: '$1.26',
      pricePercentage: '3.2%',
      marketCap: '$54,563,769,793',
      rank: 7,
      rankName: 'enj',
      img: imagePath.Usdcoin,
    },
    {
      id: 8,
      currencyName: 'Merit Circle',
      price24h: '$1.26',
      pricePercentage: '3.2%',
      marketCap: '$54,563,769,793',
      rank: 8,
      rankName: 'rnc',
      img: imagePath.XRP,
    },
  ],
};
