import imagePath from '../constants/imagePath';

export default {
  LongTerm: [
    {
      coinName: 'BitCoin',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c4,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'SCRTUSD',
      time: 'Sep-14 10:45 AM',
      img: imagePath.c1,
      risk: 'Mid Risk',
      entry: '0.57',
      stop: '0.03',
    },
    {
      coinName: 'OXTUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c2,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'MATICUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c5,
      risk: 'Mid Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'ANTIUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c1,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'DGUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c6,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
  ],
  ShortTerm: [
    {
      coinName: 'FIOUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c1,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'SCRTUSD',
      time: 'Sep-14 10:45 AM',
      img: imagePath.c2,
      risk: 'Mid Risk',
      entry: '0.57',
      stop: '0.03',
    },
    {
      coinName: 'OXTUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c3,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'BAKEUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c4,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'WTCUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c5,
      risk: 'High Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'MATICUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c6,
      risk: 'Mid Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'ANTIUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c2,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'DGUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c3,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
  ],
  Archived: [
    {
      coinName: 'FIOUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c4,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'SCRTUSD',
      time: 'Sep-14 10:45 AM',
      img: imagePath.c3,
      risk: 'Mid Risk',
      entry: '0.57',
      stop: '0.03',
    },
    {
      coinName: 'OXTUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c2,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'BAKEUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c1,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'WTCUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c5,
      risk: 'High Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'MATICUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c6,
      risk: 'Mid Risk',
      entry: '0.062',
      stop: '0.052',
    },
    {
      coinName: 'ANTIUSD',
      time: 'Oct-04 11:45 PM',
      img: imagePath.c2,
      risk: 'Low Risk',
      entry: '0.062',
      stop: '0.052',
    },
  ],
};
