export default {
  INITAIL_SCREEN: 'initailScreen',
  LOGIN: 'login',
  SIGNUP: 'signUp',
  HOME: 'home',
  PROFILE: 'Profile',
  Signals: 'Signals',
  Insingts: 'Insingts',
  Library: 'Library',
  Social: 'Social',
  TabRoutes: 'TabRoutes',
  DetailArticle: 'DetailArticle',
  AllArticles: 'AllArticles',
  Setting: 'Setting',
  ContactUs: 'ContactUs',
  ChangePassword: 'ChangePassword',
  PrivacyPolicy: 'PrivacyPolicy',
  TermsOfUse: 'TermsOfUse',
  EditProfile: 'EditProfile',
  HowToUseApp: 'HowToUseApp',
  SignalResult: 'SignalResult',
  CryptoCategories: 'CryptoCategories',
  IdoDrawerScreen: 'IdoDrawerScreen',
  CompoundCalculator: 'CompoundCalculator',
  Notification: 'Notification',
  Message: 'Message',
  SocialProfile: 'SocialProfile',
};
